
services:
  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mf-navbar
      - mf-counter
      - mf-character
      - mf-character-detail
  mf-navbar:
    build:
      context: ./mf-navbar
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  mf-counter:
    build:
      context: ./mf-counter
      dockerfile: Dockerfile
    ports:
      - 8082:8082
  mf-character:
    build:
      context: ./mf-character
      dockerfile: Dockerfile
    ports:
      - 8083:8083
  mf-character-detail:
    build:
      context: ./mf-characterDetail
      dockerfile: Dockerfile
    ports:
      - 8084:8084